apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mysql
data:
  init.sql: |
    USE app_db;
    CREATE TABLE counter (
        id INT AUTO_INCREMENT PRIMARY KEY,
        value INT
    );